# Generated by Django 5.0.1 on 2024-02-06 04:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fertilizer_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('cropid', models.AutoField(primary_key=True, serialize=False)),
                ('cropname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExtensionOfficer',
            fields=[
                ('officerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmerid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField()),
                ('registeredby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extensionofficer')),
            ],
        ),
        migrations.CreateModel(
            name='FarmParcel',
            fields=[
                ('parcelid', models.AutoField(primary_key=True, serialize=False)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('size', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('moisture', models.FloatField()),
                ('soiltype', models.CharField(max_length=50)),
                ('ph', models.FloatField()),
                ('nitrogenlevel', models.FloatField()),
                ('potassiumlevel', models.FloatField()),
                ('phosphoruslevel', models.FloatField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmer')),
            ],
        ),
        migrations.DeleteModel(
            name='Fertilizer',
        ),
        migrations.AddField(
            model_name='extensionofficer',
            name='registered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.farmer'),
        ),
    ]
