# Generated by Django 5.0.1 on 2024-02-06 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_crop_extensionofficer_farmer_farmparcel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionofficer',
            name='registered',
        ),
    ]
