# Generated by Django 5.0.1 on 2024-02-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_extensionofficer_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionofficer',
            name='officerid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='farmerid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
